root = "/home/edgarl/go/src/github.com/hinshun/image2ipfs/tmp/containerd/root"
state = "/home/edgarl/go/src/github.com/hinshun/image2ipfs/tmp/containerd/state"
oom_score = 0

[grpc]
  address = "/home/edgarl/go/src/github.com/hinshun/image2ipfs/tmp/containerd/containerd.sock"
  uid = 0
  gid = 0

[debug]
  address = "/home/edgarl/go/src/github.com/hinshun/image2ipfs/tmp/containerd/debug.sock"
  uid = 0
  gid = 0
  level = "info"

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[plugins]
  [plugins.cgroups]
    no_prometheus = false
  [plugins.diff]
    default = ["walking"]
  [plugins.linux]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = ""
    no_shim = false
    shim_debug = false
  [plugins.scheduler]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = 0
    startup_delay = "100ms"
